// Mocks generated by Mockito 5.4.4 from annotations
// in expense_tracker_app_bloc/test/src/features/home/data/repositories/account_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:expense_tracker_app_bloc/src/features/home/data/datasources/home_firebase_datasource.dart'
    as _i2;
import 'package:expense_tracker_app_bloc/src/features/home/data/datasources/home_firestore_datasource.dart'
    as _i3;
import 'package:expense_tracker_app_bloc/src/features/home/data/dto/expense.dart'
    as _i7;
import 'package:expense_tracker_app_bloc/src/features/home/data/dto/income.dart'
    as _i6;
import 'package:expense_tracker_app_bloc/src/features/home/data/dto/transaction.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeFirebaseDataScource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeFirebaseDataScource extends _i1.Mock
    implements _i2.HomeFirebaseDataScource {}

/// A class which mocks [HomeFirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeFirestoreDataSource extends _i1.Mock
    implements _i3.HomeFirestoreDataSource {
  @override
  _i4.Future<Map<String, dynamic>> fetchAccountDetails(
    String? uid,
    String? accountId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAccountDetails,
          [
            uid,
            accountId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchAccountTransactions(
    String? uid,
    String? accountId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAccountTransactions,
          [
            uid,
            accountId,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> deleteTransaction(
    String? uid,
    String? accountId,
    _i5.TransactionDto? transactionDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [
            uid,
            accountId,
            transactionDto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteIncome(
    String? uid,
    String? accountId,
    _i6.IncomeDto? incomeEntity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIncome,
          [
            uid,
            accountId,
            incomeEntity,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExpense(
    String? uid,
    String? accountId,
    _i7.ExpenseDto? expenseEntity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [
            uid,
            accountId,
            expenseEntity,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addExpense(
    String? uid,
    String? accountId,
    _i7.ExpenseDto? expenseDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [
            uid,
            accountId,
            expenseDto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addIncome(
    String? uid,
    String? accountId,
    _i6.IncomeDto? incomeDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIncome,
          [
            uid,
            accountId,
            incomeDto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
