name: expense_tracker_app_bloc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc_presentation: ^1.0.0
  cloud_firestore: ^4.15.3
  cloud_functions: ^4.6.4
  control_style: ^0.1.0
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.4.8
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  firebase_storage: ^11.6.5
  firebase_storage_mocks: ^0.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  fpdart: ^1.1.0
  get_it: ^7.6.7
  go_router: ^13.1.0
  mockito: ^5.4.4

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
