// Mocks generated by Mockito 5.4.4 from annotations
// in expense_tracker_app_bloc/test/src/features/viewall/presentation/blocs/viewall_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:expense_tracker_app_bloc/src/core/error/failures.dart' as _i5;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/entities/expense.dart'
    as _i7;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/entities/expenses_details.dart'
    as _i6;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/entities/income.dart'
    as _i11;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/entities/incomes_details.dart'
    as _i10;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/usecases/delete_expense.dart'
    as _i2;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/usecases/delete_income.dart'
    as _i9;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/usecases/fetch_expenses_details.dart'
    as _i12;
import 'package:expense_tracker_app_bloc/src/features/viewall/domain/usecases/fetch_incomes_details.dart'
    as _i13;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DeleteExpense].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteExpense extends _i1.Mock implements _i2.DeleteExpense {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>> call({
    required String? accountId,
    required _i7.ExpenseEntity? expenseEntity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #accountId: accountId,
            #expenseEntity: expenseEntity,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #accountId: accountId,
              #expenseEntity: expenseEntity,
            },
          ),
        )),
        returnValueForMissingStub: _i3
            .Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #accountId: accountId,
              #expenseEntity: expenseEntity,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>);
}

/// A class which mocks [DeleteIncome].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteIncome extends _i1.Mock implements _i9.DeleteIncome {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>> call({
    required String? accountId,
    required _i11.IncomeEntity? incomeEntity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #accountId: accountId,
            #incomeEntity: incomeEntity,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #accountId: accountId,
              #incomeEntity: incomeEntity,
            },
          ),
        )),
        returnValueForMissingStub: _i3
            .Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #accountId: accountId,
              #incomeEntity: incomeEntity,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>);
}

/// A class which mocks [FetchExpensesDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchExpensesDetails extends _i1.Mock
    implements _i12.FetchExpensesDetails {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>> call(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub: _i3
            .Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.ExpensesDetailsEntity>>);
}

/// A class which mocks [FetchIncomesDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchIncomesDetails extends _i1.Mock
    implements _i13.FetchIncomesDetails {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>> call(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub: _i3
            .Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i10.IncomesDetailsEntity>>);
}
