// Mocks generated by Mockito 5.4.4 from annotations
// in expense_tracker_app_bloc/test/src/features/authentication/presentation/blocs/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:expense_tracker_app_bloc/src/core/error/failures.dart' as _i5;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/entities/user.dart'
    as _i6;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/entities/user_signup_details.dart'
    as _i10;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/usecases/delete_user.dart'
    as _i13;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/usecases/is_signed_in_user.dart'
    as _i2;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/usecases/recover_password.dart'
    as _i12;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/usecases/sign_in_user.dart'
    as _i8;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/usecases/sign_out_user.dart'
    as _i11;
import 'package:expense_tracker_app_bloc/src/features/authentication/domain/usecases/sign_up_user.dart'
    as _i9;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IsSignedInUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsSignedInUser extends _i1.Mock implements _i2.IsSignedInUser {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity?>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity?>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>>);
}

/// A class which mocks [SignInUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUser extends _i1.Mock implements _i8.SignInUser {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> call(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);
}

/// A class which mocks [SignUpUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUser extends _i1.Mock implements _i9.SignUpUser {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> call(
          _i10.UserSignUpDetailsEntity? userDetails) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [userDetails],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
          this,
          Invocation.method(
            #call,
            [userDetails],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
          this,
          Invocation.method(
            #call,
            [userDetails],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);
}

/// A class which mocks [SignOutUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUser extends _i1.Mock implements _i11.SignOutUser {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [RecoverPassword].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecoverPassword extends _i1.Mock implements _i12.RecoverPassword {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [email],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #call,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #call,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [DeleteUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUser extends _i1.Mock implements _i13.DeleteUser {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(String? password) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [password],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #call,
            [password],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #call,
            [password],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
